project_id = "gqibxsjcspmzjhrtnqnf"

[functions.chat]
verify_jwt = false

[functions.transfer-credits]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
